# Generated by Django 3.0 on 2020-03-02 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备ID')),
                ('device_name', models.CharField(default='新设备', max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_online_time', models.DateTimeField(auto_now=True, verbose_name='上一次上线时间')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Info', '信息'), ('Warning', '警告'), ('Error', '错误')], max_length=50, verbose_name='类型')),
                ('message', models.CharField(max_length=50, verbose_name='内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Device')),
            ],
        ),
    ]
