# Generated by Django 3.0 on 2020-03-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='type',
        ),
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('malfunction', '故障')], default='offline', max_length=50, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误')], default='info', max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_online_time',
            field=models.DateTimeField(verbose_name='上一次上线时间'),
        ),
    ]
