# Generated by Django 2.1.7 on 2020-04-02 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200312_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_online_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上一次上线时间'),
        ),
    ]
