# Generated by Django 2.1.7 on 2020-04-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200402_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='outcome',
            field=models.CharField(choices=[('default', ''), ('nonempty', '非空'), ('empty', '空')], default='default', max_length=50, verbose_name='结果'),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_online_time',
            field=models.DateTimeField(default=None, verbose_name='上一次上线时间'),
        ),
    ]
