# Generated by Django 2.1.7 on 2020-04-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200404_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='reset_status',
            field=models.CharField(choices=[('no', '未重置'), ('yes', '已重置')], default='no', max_length=50, verbose_name='重置状态'),
        ),
    ]
