# Generated by Django 2.1.7 on 2020-04-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_device_reset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order_todo',
            field=models.CharField(default='', max_length=100, verbose_name='命令'),
        ),
    ]
