# Generated by Django 2.1.7 on 2020-04-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_device_order_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order_outcome',
            field=models.CharField(default='', max_length=50, verbose_name='命令结果'),
        ),
        migrations.AlterField(
            model_name='device',
            name='order_todo',
            field=models.CharField(default='', max_length=50, verbose_name='命令'),
        ),
    ]
