# Generated by Django 2.1 on 2020-04-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20200406_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time_limit',
            field=models.CharField(default='', max_length=50, verbose_name='时间限制'),
        ),
        migrations.AddField(
            model_name='log',
            name='type_limit',
            field=models.CharField(default='', max_length=50, verbose_name='类型限制'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_status',
            field=models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('malfunction', '故障')], default='offline', max_length=50, verbose_name='设备状态"'),
        ),
        migrations.AlterField(
            model_name='log',
            name='level',
            field=models.CharField(choices=[('info', '信息'), ('purpose', '提示'), ('warning', '警告'), ('error', '错误')], default='info', max_length=50, verbose_name='类型'),
        ),
    ]
