# Generated by Django 2.1 on 2020-04-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20200421_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='time_limit',
        ),
        migrations.RemoveField(
            model_name='device',
            name='type_limit',
        ),
    ]
