# Generated by Django 2.1 on 2020-04-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20200421_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='area',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Device'), max_length=50, verbose_name='监管区域'),
        ),
    ]
