# Generated by Django 2.1 on 2020-04-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_remove_log_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='area',
            field=models.CharField(default='', max_length=50, verbose_name='监管区域'),
        ),
    ]
