# Generated by Django 2.1 on 2020-05-14 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20200503_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(default='测试区域', max_length=100, verbose_name='监管区域'),
        ),
    ]
